export const TESTIMONIALS = [
    {
        name: "Sarah Mitchell",
        role: "CEO",
        company: "TechStart Innovations",
        companyUrl: "https://techstart.com",
        image: "/images/testimonials/person1.jpg",
        content: "Their AI solutions transformed our operations, delivering results beyond our expectations. Truly exceptional partnership.",
        time: "3:45 PM",
        date: "Dec 15, 2025",
    },
    {
        name: "David Chen",
        role: "Founder",
        company: "GrowthLabs",
        companyUrl: "https://growthlabs.com",
        image: "/images/testimonials/person2.jpg",
        content: "The startup guidance and technical expertise helped us scale from idea to successful product launch in record time.",
        time: "11:10 AM",
        date: "Nov 28, 2025",
    },
    {
        name: "Emily Rodriguez",
        role: "Marketing Director",
        company: "BrandFlow",
        companyUrl: "https://brandflow.com",
        image: "/images/testimonials/person3.jpg",
        content: "Their digital marketing strategies delivered a 300% increase in qualified leads. Outstanding results and professionalism.",
        time: "9:30 AM",
        date: "Oct 20, 2025",
    },
    {
        name: "Michael Park",
        role: "CTO",
        company: "FinTech Solutions",
        companyUrl: "https://fintechsol.com",
        image: "/images/testimonials/person4.jpg",
        content: "The mobile app they built is robust, beautiful, and our users love it. Best development team we've worked with.",
        time: "2:00 PM",
        date: "Sep 12, 2025",
    },
    {
        name: "Jessica Williams",
        role: "Product Manager",
        company: "CloudVenture",
        companyUrl: "https://cloudventure.com",
        image: "/images/testimonials/person1.jpg",
        content: "From concept to deployment, their web development expertise ensured our platform launched flawlessly and on schedule.",
        time: "4:15 PM",
        date: "Aug 5, 2025",
    },
    {
        name: "Robert Kumar",
        role: "Head of Innovation",
        company: "DataStream Corp",
        companyUrl: "https://datastream.com",
        image: "/images/testimonials/person2.jpg",
        content: "Their AI and machine learning solutions gave us competitive advantages we didn't think possible. Truly innovative.",
        time: "1:20 PM",
        date: "Jul 18, 2025",
    },
];
